import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Login Page',
  description: 'Generated by create next app',
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section className="p-10">{children}</section>;
}
